# .github/workflows/data_pipeline.yml
name: Data Pipeline Demo

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  run-pipeline:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas requests

      - name: Run data pipeline
        run: python scripts/data_pipeline.py

      - name: Upload processed data
        uses: actions/upload-artifact@v4
        with:
          name: processed-data
          path: output/
          if-no-files-found: error
          retention-days: 14
          compression-level: 6
